### ISSUE TITLE
Should PropertiesRepository be singleton

### ISSUE THREAD

**Issue by viki85in** [josh28/kontext#2]
PropertiesRepository is injected into dependent modules. Instances are created as and when required (during instantiation of module classes).

Why not make it into singleton?
1. Every instance of PropertiesRepository have the same state. So, why not just enforce single instance of PropertiesRepository?
2. Need to avoid dirty reads and writes. If it so happens that one instance changes the value of a property, another instance should have it instantly. Redis may come into picture. But for the time being, Cassandra (or Mongo) will suffice.

**Comment by josh-petite** [comment]
We can do that. I can refactor it in a new branch.

**Comment by viki85in** [comment]
Don't worry about it now if you are working on something else. I was merely thinking out aloud (in writing).

**Comment by viki85in** [comment]
We have a singleton properties repository in place. Works well.
